CREATE FUNCTION sp_get_users()
RETURNS TABLE
(
	id CHARACTER VARYING, FULLNAME CHARACTER VARYING,  EMAIL CHARACTER VARYING
)
LANGUAGE 'plpgsql'

AS
$BODY$
	BEGIN
		RETURN QUERY
			SELECT USERS.ID as "a", USERS.FULLNAME as "b", USERS.EMAIL as "c" FROM USERS;
	END;
$BODY$

